const mdata = [
    {
        Item_Id:1234134,
        Item_Name:"abc",
        Item_Photo_URL:"abcdefghijklmnopqrstuvwxyz",
        Item_Description:"no",
        Item_Category:"xyz",
        Item_Price:275
    },
    {
        Item_Id:1234134,
        Item_Name:"abc",
        Item_Photo_URL:"abcdefghijklmnopqrstuvwxyz",
        Item_Description:"no",
        Item_Category:"xyz",
        Item_Price:275
    },   
    {
        Item_Id:1234134,
        Item_Name:"abc",
        Item_Photo_URL:"abcdefghijklmnopqrstuvwxyz",
        Item_Description:"no",
        Item_Category:"xyz",
        Item_Price:275
    },   
    {
        Item_Id:1234134,
        Item_Name:"abc",
        Item_Photo_URL:"abcdefghijklmnopqrstuvwxyz",
        Item_Description:"no",
        Item_Category:"xyz",
        Item_Price:275
    },      
    {
        Item_Id:1234134,
        Item_Name:"abc",
        Item_Photo_URL:"abcdefghijklmnopqrstuvwxyz",
        Item_Description:"no",
        Item_Category:"xyz",
        Item_Price:275
    },
    {
        Item_Id:1234134,
        Item_Name:"abc",
        Item_Photo_URL:"abcdefghijklmnopqrstuvwxyz",
        Item_Description:"no",
        Item_Category:"xyz",
        Item_Price:275
    },
    {
        Item_Id:1234134,
        Item_Name:"abc",
        Item_Photo_URL:"abcdefghijklmnopqrstuvwxyz",
        Item_Description:"no",
        Item_Category:"xyz",
        Item_Price:275
    },
    {
        Item_Id:1234134,
        Item_Name:"abc",
        Item_Photo_URL:"abcdefghijklmnopqrstuvwxyz",
        Item_Description:"no",
        Item_Category:"xyz",
        Item_Price:275
    },
    {
        Item_Id:1234134,
        Item_Name:"abc",
        Item_Photo_URL:"abcdefghijklmnopqrstuvwxyz",
        Item_Description:"no",
        Item_Category:"xyz",
        Item_Price:275
    },
    {
        Item_Id:1234134,
        Item_Name:"abc",
        Item_Photo_URL:"abcdefghijklmnopqrstuvwxyz",
        Item_Description:"no",
        Item_Category:"xyz",
        Item_Price:275
    },
    {
        Item_Id:1234134,
        Item_Name:"abc",
        Item_Photo_URL:"abcdefghijklmnopqrstuvwxyz",
        Item_Description:"no",
        Item_Category:"xyz",
        Item_Price:275
    },
    {
        Item_Id:1234134,
        Item_Name:"abc",
        Item_Photo_URL:"abcdefghijklmnopqrstuvwxyz",
        Item_Description:"no",
        Item_Category:"xyz",
        Item_Price:275
    },
    {
        Item_Id:1234134,
        Item_Name:"abc",
        Item_Photo_URL:"abcdefghijklmnopqrstuvwxyz",
        Item_Description:"no",
        Item_Category:"xyz",
        Item_Price:275
    },
    {
        Item_Id:1234134,
        Item_Name:"abc",
        Item_Photo_URL:"abcdefghijklmnopqrstuvwxyz",
        Item_Description:"no",
        Item_Category:"xyz",
        Item_Price:275
    },
    {
        Item_Id:1234134,
        Item_Name:"abc",
        Item_Photo_URL:"abcdefghijklmnopqrstuvwxyz",
        Item_Description:"no",
        Item_Category:"xyz",
        Item_Price:275
    },
]

export default mdata;