const Sdata = [
    {
        table_id:1,
        pending:4,
        accsept:7,
        delivered:2
    },
    {
        table_id:2,
        pending:7,
        accsept:4,
        delivered:3
    },
    {
        table_id:3,
        pending:5,
        accsept:3,
        delivered:1
    },
    {
        table_id:3,
        pending:5,
        accsept:3,
        delivered:1
    },
    {
        table_id:3,
        pending:5,
        accsept:3,
        delivered:1
    },
    {
        table_id:3,
        pending:5,
        accsept:3,
        delivered:1
    },
    {
        table_id:3,
        pending:5,
        accsept:3,
        delivered:1
    },
    {
        table_id:3,
        pending:5,
        accsept:3,
        delivered:1
    },
    {
        table_id:4,
        pending:2,
        accsept:5,
        delivered:3
    },
]

export default Sdata;